# Generated by Django 5.2.4 on 2025-07-29 04:55

from django.db import migrations

# List of all Indian States and Union Territories
INDIAN_STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
]

def populate_states(apps, schema_editor):
    """
    This function gets the State model and populates it with the list of Indian states.
    """
    State = apps.get_model('portal', 'State')
    for state_name in INDIAN_STATES:
        State.objects.create(name=state_name)

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'), # This should match the previous migration file
    ]

    operations = [
        migrations.RunPython(populate_states),
    ]
